# Generated by Django 2.2.19 on 2021-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210826_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
